---
- name: check resolvconf
  shell: which resolvconf
  register: resolvconf
  ignore_errors: yes
  changed_when: false

- set_fact:
    resolvconf: >-
      {%- if resolvconf.rc == 0 -%}true{%- else -%}false{%- endif -%}

- name: target resolv.conf file
  set_fact:
    resolvconffile: >-
      {%- if resolvconf|bool -%}/etc/resolvconf/resolv.conf.d/head{%- else -%}/etc/resolv.conf{%- endif -%}
    base: >-
      {%- if resolvconf|bool -%}/etc/resolvconf/resolv.conf.d/base{%- endif -%}
  when: ansible_os_family != "CoreOS"

- name: target dhclient conf/hook files for Red Hat family
  set_fact:
    dhclientconffile: /etc/dhclient.conf
    dhclienthookfile: /etc/dhcp/dhclient.d/zdnsupdate.sh
  when: ansible_os_family == "RedHat"

- name: target dhclient conf/hook files for Debian family
  set_fact:
    dhclientconffile: /etc/dhcp/dhclient.conf
    dhclienthookfile: /etc/dhcp/dhclient-enter-hooks.d/zdnsupdate.sh
  when: ansible_os_family == "Debian"

- name: target temporary resolvconf cloud init file
  set_fact: resolvconffile=/tmp/resolveconf_cloud_init_conf
  when: ansible_os_family == "CoreOS"

- name: generate search domains to resolvconf
  set_fact:
    searchentries:
      search {{ ([ 'default.svc.' + dns_domain, 'svc.' + dns_domain ] + searchdomains|default([])) | join(' ') }}
    prepend_search:
      prepend domain-search "{{ ([ 'default.svc.' + dns_domain, 'svc.' + dns_domain ] + searchdomains|default([])) | join('", "') }}";

- name: pick dnsmasq cluster IP
  set_fact:
    dnsmasq_server: >-
      {%- if skip_dnsmasq|bool -%}{{ [ skydns_server ] + upstream_dns_servers|default([]) }}{%- else -%}{{ [ dns_server ] }}{%- endif -%}

- name: generate nameservers to resolvconf
  set_fact:
    nameserverentries:
      nameserver {{( dnsmasq_server|default([]) + nameservers|default([])) | join(',nameserver ')}}
    prepend_nameserver:
      prepend domain-name-servers {{( dnsmasq_server|default([]) + nameservers|default([])) | join(', ') }};
